### ISSUE TITLE
Can't get offset for  CBaseServer::RejectConnection

### ISSUE THREAD

**Issue by bklol** [GAMMACASE/ServerRedirect#43]
still getting same error after update gamedata file

**Comment by GAMMACASE** [comment]
Make sure you have actually uploaded the updated gamedata to your server. Also what OS are you on?

**Comment by bklol** [comment]
im sure updated the gamedata ,im using linux and sm 1.11

**Comment by GAMMACASE** [comment]
Updated linux gamedata, for some reason my linux binary wasn't matching with the up to date one, now should be fine, as I've tested it myself. Please, reopen this issue if there are still problems with it.

**Comment by tslashd** [comment]
Getting this error with latest gamedata file on Ubuntu 20.04

@GAMMACASE (idk if you'd get notification about this)

**Comment by GAMMACASE** [comment]
> Getting this error with latest gamedata file on Ubuntu 20.04
> 
> @GAMMACASE (idk if you'd get notification about this)

Are you sure you are on the latest gamedata tho? since it does work for me on linux (tested on debian tho), can you double check that you actually using the gamedata from the master branch. if yes, then please dm me on discord GAMMACASE#1535 for continuation

**Comment by GAMMACASE** [comment]
@bklol Were you having this error originally that made you go here and search for an updated gamedata? Or did you just saw an update here and updated anyway to later figure out that it doesn't work?

**Comment by GAMMACASE** [comment]
Alright, so for anyone who is getting the same error, please read carefully:

Master branch and also the latest release contains the gamedata files for the new up to date binary of engine.so, which has following md5 checksum: adb77ee715b5949b50127999278e9dba (7 439 976 bytes). Please, make sure that you **actually** have troubles running the plugin and that you have an up to date engine.so, and only then perform gamedata update!

For anyone whos engine.so doesn't match with the up to date binary you should be able to just use old gamedata file (https://github.com/GAMMACASE/ServerRedirect/blob/5aea3624f54f285680ff63440b88f56ad920a871/addons/sourcemod/gamedata/server_redirect.games.txt) with no troubles. For clarification I also provide md5 checksum for the old binary: 19025a98f1f7a933c9d1f7f01d246900 (7 438 568 bytes).

If you still experiencing troubles and getting this error after doing what is said in the above paragraphs, please, reply here with the information of what OS are you running and leave an md5 checksum (with the full byte size of it) of the bin/engine.so that your server is using.

I'll leave this issue open for quite some time until the next CSGO update hits, so anyone who's wondering can read through and not open a new issue about it.

**Comment by GAMMACASE** [comment]
Alright, new csgo update has dropped and I expect every server to be using latest binaries already, so hopefully there would be no reports of this in the near future.
